/* Copy / cut / paste of rules and Do statements: parsing, storage, checks, pasting.  node v2/test/clip.js */
global.window = global; global.DC = {};
require('../../js/expr.js'); require('../kernel.js');
for (const f of ['space', 'platformer', 'combat', 'dialogue', 'farm', 'stealth']) require('../ext/' + f + '.js');
require('../studio/core.js'); require('../studio/clip.js'); require('../studio/starters.js');
const S = DC2.studio, C = S.clip, ST = window.DC2_STARTERS, reg = S.allReg();
let pass = 0, fail = 0;
const ok = (cond, name, extra) => { if (cond) pass++; else { fail++; console.log('  ✗', name, extra === undefined ? '' : JSON.stringify(extra).slice(0, 300)); } };
const section = (t) => console.log('\n' + t);
const game = () => new S.Doc(S.clone(ST['flag-of-gold'].cart));
const errs = (d) => S.check(d.cart).errors.map((e) => e.path + ': ' + e.msg);
const mem = () => { const d = {}; return { getItem: (k) => (k in d ? d[k] : null), setItem: (k, v) => { d[k] = String(v); }, removeItem: (k) => { delete d[k]; }, d }; };
const RULE = { on: 'button', button: 'a', then: [{ act: 'sound', id: 'coin' }, { act: 'add', path: 'coins', by: 1 }] };
const ACT = { act: 'sound', id: 'coin' };

section('1. reading pasted text');
let r = C.parse(JSON.stringify(RULE)); ok(r.kind === 'rule' && r.items.length === 1 && r.items[0].on === 'button', 'a bare rule');
r = C.parse(JSON.stringify(ACT)); ok(r.kind === 'actions' && r.items[0].act === 'sound', 'a bare action');
r = C.parse(JSON.stringify([RULE, RULE])); ok(r.kind === 'rule' && r.items.length === 2, 'a list of rules');
r = C.parse(JSON.stringify([ACT, { act: 'wait', t: 1 }])); ok(r.kind === 'actions' && r.items.length === 2, 'a list of actions');
r = C.parse(JSON.stringify({ rules: [RULE], c: {} })); ok(r.kind === 'rule' && r.items.length === 1, 'a whole thing with a "rules" list gives its rules');
r = C.parse('```json\n' + JSON.stringify(RULE, null, 2) + '\n```'); ok(r.kind === 'rule', 'wrapped in code fences, as chat answers are');
r = C.parse('  \n ' + JSON.stringify(ACT) + '\n\n'); ok(r.kind === 'actions', 'with spaces around');
r = C.parse(JSON.stringify({ dcClip: 1, kind: 'rule', items: [RULE] })); ok(r.kind === 'rule', 'what the Studio itself copies');
ok(/damaged/.test(C.parse(JSON.stringify({ dcClip: 1, kind: 'rule', items: [] })).error), 'a damaged copy is refused');
ok(/not valid JSON/.test(C.parse('{on: button').error), 'text that is not JSON says so');
ok(/nothing to paste/.test(C.parse('   ').error) && /nothing to paste/.test(C.parse(null).error), 'nothing');
ok(/mixes/.test(C.parse(JSON.stringify([RULE, ACT])).error), 'rules and actions mixed');
ok(/neither/.test(C.parse(JSON.stringify({ hello: 1 })).error), 'an object that is neither');
ok(C.parse('42').error && C.parse('"on"').error && C.parse('[]').error && C.parse('[1,2]').error, 'numbers, words and empty lists are not rules');
r = C.parse(JSON.stringify({ act: 'if', test: 'x', then: [{ act: 'sound', id: 'coin' }] })); ok(r.kind === 'actions' && r.items[0].then.length === 1, 'an action that holds other actions');

section('2. the clipboard remembers');
global.localStorage = mem(); delete global.navigator;
ok(C.get() === null, 'empty to begin with');
C.set('rule', [RULE]); let g = C.get();
ok(g && g.kind === 'rule' && g.items[0].on === 'button' && g.dcClip === 1, 'a copied rule comes back');
const src = S.clone(RULE); C.set('rule', [src]); src.then.push({ act: 'log' }); ok(C.get().items[0].then.length === 2, 'it is a copy: changing the original afterwards changes nothing');
const got = C.get(); got.items[0].then.length = 0; ok(C.get().items[0].then.length === 2, 'and changing what you get back changes nothing either');
C.set('actions', [ACT, ACT]); ok(C.get().kind === 'actions' && C.get().items.length === 2, 'actions too, one or several');
ok(JSON.parse(localStorage.d[C.KEY]).kind === 'actions', 'kept in the browser');
let threw = false; try { C.set('rule', []); } catch (e) { threw = true; } ok(threw, 'copying nothing is an error');
threw = false; try { C.set('rule', [ACT]); } catch (e) { threw = true; } ok(threw, 'and so is a rule that is not a rule');
localStorage.setItem(C.KEY, '{broken'); ok(C.get() && C.get().kind === 'actions', 'damaged saved data falls back to what was copied this visit');
C.clear(); ok(C.get() === null && !(C.KEY in localStorage.d), 'cleared');
global.localStorage = { getItem() { throw new Error('no'); }, setItem() { throw new Error('no'); }, removeItem() { throw new Error('no'); } };
C.set('rule', [RULE]); ok(C.get() && C.get().kind === 'rule', 'when the browser will not store anything it still works until you leave');
C.clear(); global.localStorage = mem();
let written = null; global.navigator = { clipboard: { writeText: (t) => { written = t; return Promise.resolve(); } } };
C.set('rule', [RULE]); ok(written && JSON.parse(written).items[0].on === 'button', 'it is also put on the device clipboard as JSON');
ok(C.parse(written).kind === 'rule', 'and that text can be pasted back in');
global.navigator = { clipboard: { writeText: () => { throw new Error('denied'); } } }; let bad = false; try { C.set('rule', [RULE]); } catch (e) { bad = true; } ok(!bad, 'a device clipboard that refuses does not break copying');
delete global.navigator;
ok(C.describe(null) === '' && C.describe({ kind: 'rule', items: [RULE] }) === 'rule “button”' && C.describe({ kind: 'rule', items: [RULE, RULE] }) === '2 rules' && C.describe({ kind: 'actions', items: [ACT] }) === 'action “sound”' && C.describe({ kind: 'actions', items: [ACT, ACT, ACT] }) === '3 actions', 'plain-words descriptions for buttons');

section('3. can it go there?');
ok(C.checkRules([RULE], 'entity', reg) === null && C.checkRules([RULE], 'scene', reg) === null, 'a button rule fits a thing and a level');
ok(/touch.*things.*not on levels/i.test(C.checkRules([{ on: 'touch', then: [] }], 'scene', reg)), 'a "touch" rule does not belong on a level, and says why', C.checkRules([{ on: 'touch', then: [] }], 'scene', reg));
ok(C.checkRules([{ on: 'touch', then: [] }], 'entity', reg) === null && C.checkRules([{ on: 'start', then: [] }], 'scene', reg) === null, 'but fits a thing; a "start" rule fits a level');
ok(/start/i.test(C.checkRules([{ on: 'start', then: [] }], 'entity', reg) || ''), '"start" is for levels, not things');
ok(/don't know the trigger “banana”/.test(C.checkRules([{ on: 'banana', then: [] }], 'entity', reg)), 'an unknown trigger');
ok(/don't know the action “fly”/.test(C.checkRules([{ on: 'button', then: [{ act: 'fly' }] }], 'entity', reg)), 'an unknown action inside a rule');
ok(/don't know the action “fly”/.test(C.checkRules([{ on: 'button', then: [], else: [{ act: 'fly' }] }], 'entity', reg)), 'also in "otherwise"');
ok(C.checkActions([ACT], reg) === null && /“fly”/.test(C.checkActions([{ act: 'if', test: '1', then: [{ act: 'fly' }] }], reg)), 'actions are checked all the way down');
ok(C.exts([ACT], 'actions', reg).length === 0, 'plain actions need no extension');
ok(C.exts([{ act: 'give', item: 'x' }], 'actions', reg).join() === 'economy', 'an economy action needs the economy extension');
ok(C.exts([{ on: 'spotted', then: [{ act: 'give', item: 'x' }] }], 'rule', reg).sort().join() === 'economy,stealth', 'a rule needs its trigger\'s extension and its actions\'');
ok(C.exts([{ act: 'if', test: '1', then: [{ act: 'give', item: 'x' }] }], 'actions', reg).join() === 'economy', 'including inside other actions');

section('4. pasting');
let d = game(), hero = d.cart.meta.player, path = ['prefabs', hero, 'rules'], n0 = d.cart.prefabs[hero].rules.length, u0 = d.undos.length;
let at = C.paste(d, reg, path, null, { kind: 'rule', items: [RULE] });
ok(at === n0 && d.cart.prefabs[hero].rules.length === n0 + 1 && d.cart.prefabs[hero].rules[n0].on === 'button', 'pasted at the end');
ok(d.undos.length === u0 + 1, 'in one undo step'); d.undo(); ok(d.cart.prefabs[hero].rules.length === n0, 'which undoes');
C.paste(d, reg, path, 1, { kind: 'rule', items: [RULE, { on: 'every', t: 2, then: [] }] });
const ons = d.cart.prefabs[hero].rules.map((x) => x.on); ok(ons[1] === 'button' && ons[2] === 'every' && ons.length === n0 + 2, 'pasted at a place, in order, pushing the rest down', ons);
const pasted = d.cart.prefabs[hero].rules[1]; pasted.then.length = 0; ok(RULE.then.length === 2, 'pasted rules are separate copies');
d = game(); C.paste(d, reg, path, 0, { kind: 'rule', items: [RULE] }); ok(errs(d).length === 0, 'a rule pasted into the same project is valid', errs(d));
d = game(); const sp = ['scenes', 'cave', 'rules']; ok(d.cart.scenes.cave.rules === undefined || d.cart.scenes.cave.rules.length === 0, 'a level can start with no rules at all');
C.paste(d, reg, sp, null, { kind: 'rule', items: [RULE] }); ok(Array.isArray(d.cart.scenes.cave.rules) && d.cart.scenes.cave.rules.length === 1 && errs(d).length === 0, 'pasting into a level with no rule list creates it');
d = game(); const rp = ['prefabs', hero, 'rules', 0, 'then'], len0 = d.cart.prefabs[hero].rules[0].then.length;
C.paste(d, reg, rp, 0, { kind: 'actions', items: [ACT, { act: 'wait', t: 0.1 }] });
ok(d.cart.prefabs[hero].rules[0].then.length === len0 + 2 && d.cart.prefabs[hero].rules[0].then[0].act === 'sound' && d.cart.prefabs[hero].rules[0].then[1].act === 'wait', 'actions go into a rule\'s "Then" at a place, in order');
C.paste(d, reg, rp, null, { kind: 'actions', items: [ACT] }); ok(d.cart.prefabs[hero].rules[0].then.slice(-1)[0].act === 'sound', 'or at the end');
d = game(); ok(!d.cart.meta.extensions.includes('economy'), 'this project has no economy extension');
C.paste(d, reg, rp, null, { kind: 'actions', items: [{ act: 'give', item: 'key' }] });
ok(d.cart.meta.extensions.includes('economy'), 'pasting an economy action turns the economy extension on, like adding one would');
d = game(); C.paste(d, reg, path, null, { kind: 'rule', items: [{ on: 'spotted', then: [{ act: 'log', text: 'x' }] }] });
ok(d.cart.meta.extensions.includes('stealth'), 'and a stealth rule turns on stealth');
d = game(); d.cart.meta.extensions = d.cart.meta.extensions.concat(['economy']); const before = d.cart.meta.extensions.length; C.paste(d, reg, rp, null, { kind: 'actions', items: [{ act: 'give', item: 'key' }] });
ok(d.cart.meta.extensions.length === before, 'an extension that is already on is not added twice');

section('5. what comes with it when it lands somewhere that does not have what it points to');
d = game(); C.paste(d, reg, path, null, { kind: 'rule', items: [{ on: 'button', button: 'a', then: [{ act: 'sound', id: 'coin' }] }] });
ok(C.problems(d.cart, path, d.cart.prefabs[hero].rules.length - 1, 1) === 0, 'a sound this project has: no problems');
d = game(); C.paste(d, reg, path, null, { kind: 'rule', items: [{ on: 'button', button: 'a', then: [{ act: 'sound', id: 'does-not-exist' }] }] });
ok(C.problems(d.cart, path, d.cart.prefabs[hero].rules.length - 1, 1) >= 1, 'a sound it does not have: counted, so you can be told');
ok(C.problems(d.cart, path, 0, 1) === 0, 'and only the pasted rule is blamed');
d = game(); C.paste(d, reg, rp, null, { kind: 'actions', items: [{ act: 'sound', id: 'nope' }, { act: 'sound', id: 'nope2' }] });
ok(C.problems(d.cart, rp, d.cart.prefabs[hero].rules[0].then.length - 2, 2) >= 2, 'two pasted actions with problems are both counted');

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
