"""Browser checks for the Sound tab, the sound-effect editor and the music (piano roll) editor, with real mouse input."""
import asyncio
from playwright.async_api import async_playwright
URL = 'http://localhost:8123/v2/studio.html'
P = F = 0
def ck(n, c, x=''):
    global P, F
    if c: P += 1
    else: F += 1; print('  ✗', n, x)

async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(args=['--autoplay-policy=no-user-gesture-required'])
        ctx = await b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, has_touch=True, is_mobile=True)
        pg = await ctx.new_page(); errs = []
        pg.on('pageerror', lambda e: errs.append(str(e) + ' :: ' + str(getattr(e, 'stack', ''))[:300]))
        pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' and 'status of 403' not in m.text else None)
        ev = pg.evaluate; S = 'window.DC2_STUDIO'; A = 'DC.Audio'
        await pg.goto(URL); await pg.wait_for_selector('#btnNew')
        await pg.click('#btnNew'); await pg.fill('.big-in', 'Sound test'); await pg.click('[data-tmpl=flag-of-gold]')
        await pg.wait_for_selector('#screenEditor:not([hidden])'); await pg.wait_for_timeout(300)
        # count every sound and note the engine is asked to play
        await ev("""() => { window.__plays = 0; window.__blips = []; const p = DC.Audio.play.bind(DC.Audio), bl = DC.Audio.blip.bind(DC.Audio);
          DC.Audio.play = (n, d) => { window.__plays++; return p(n, d); }; DC.Audio.blip = (w, f, d, v) => { window.__blips.push([w, Math.round(f)]); return bl(w, f, d, v); }; }""")
        async def sheet_btn(text): await pg.locator(f'.sheet button:has-text("{text}")').first.click(); await pg.wait_for_timeout(150)
        async def close_sheets():
            while await pg.locator('.sheet-title [aria-label=close]').count(): await pg.locator('.sheet-title [aria-label=close]').last.click(); await pg.wait_for_timeout(60)
        async def doc(expr): return await ev(f"{S}.doc.cart.{expr}")
        async def valid(): return await ev(f"{S}.check ? 0 : DC2.studio.check({S}.doc.cart).errors.length")
        async def errors(): return await ev(f"DC2.studio.check({S}.doc.cart).errors.map(e => e.path + ': ' + e.msg)")
        async def warnings(): return await ev(f"DC2.studio.check({S}.doc.cart).warnings.map(e => e.path + ': ' + e.msg)")
        async def peak(which, ms=800):
            m = 0
            for _ in range(ms // 20): m = max(m, await ev(f"{A}.peak('{which}')")); await pg.wait_for_timeout(20)
            return m

        # ============================================================ the Sound tab
        tabs = await ev("[...document.querySelectorAll('#tabs button')].map(b => b.dataset.tab)")
        ck('there is a Sound tab between Art and Code', tabs == ['map', 'things', 'art', 'sound', 'code', 'game', 'play'], tabs)
        await pg.click('#tabs [data-tab=sound]'); await pg.wait_for_timeout(300)
        ck('it lists every sound effect and song', await pg.locator('.sndcard[data-sound]').count() == 9 and await pg.locator('.sndcard[data-song]').count() == 2)
        ck('each shows a picture and what it is', await pg.locator('.sndcard[data-sound=coin] canvas').count() == 1 and 'Square' in await pg.locator('.sndcard[data-sound=coin] small').text_content())
        ck('sounds used by rules say so', 'used' in await pg.locator('.sndcard[data-sound=coin] small').text_content())
        ck('songs say which levels play them', 'plays in cave' in await pg.locator('.sndcard[data-song=cave] small').text_content(), await pg.locator('.sndcard[data-song=cave] small').text_content())
        n0 = await ev("window.__plays")
        await pg.click('.sndcard[data-sound=coin] .sndplay'); await pg.wait_for_timeout(50)
        ck('▶ on a sound plays it without opening it', await ev("window.__plays") == n0 + 1 and await ev("document.querySelector('#sfxEditor').hidden"))
        ck('and it really makes sound on the effects channel', await peak('sfx', 500) > 0.005)
        await pg.click('.sndcard[data-song=cave] .sndplay'); await pg.wait_for_timeout(500)
        ck('▶ on a song plays it', await ev(f"{A}.songName") == '@list' and await pg.locator('.sndcard[data-song=cave] .sndplay.on').count() == 1)
        ck('with sound on the music channel', await peak('music', 800) > 0.005)
        await pg.click('.sndcard[data-song=cave] .sndplay'); await pg.wait_for_timeout(100)
        ck('tapping again stops it', await ev(f"{A}.songName") is None)
        await pg.click('.sndcard[data-song=cave] .sndplay'); await pg.wait_for_timeout(200)
        await pg.click('#tabs [data-tab=map]'); await pg.wait_for_timeout(200)
        ck('leaving the tab stops it', await ev(f"{A}.songName") is None)
        await pg.click('#tabs [data-tab=sound]'); await pg.wait_for_timeout(200)
        await pg.click('#btnSoundMixer'); await pg.wait_for_timeout(300)
        ck('the Mixer button opens the mixer', await pg.locator('.sheet .sheet-title:has-text("Sound mixer")').count() == 1)
        ck('whose rows have an edit button', await pg.locator('.sheet .mx-edit').count() == 11)
        await pg.locator('.sheet .mx-row:has([data-mx="sound-door"]) .mx-edit').click(); await pg.wait_for_timeout(300)
        ck('that opens the sound in the editor and closes the mixer', not await ev("document.querySelector('#sfxEditor').hidden") and await ev("document.querySelector('#sfxName').textContent") == 'door' and await pg.locator('.sheet').count() == 0)
        await pg.click('#sfxBack'); await pg.wait_for_timeout(150)

        # ============================================================ making a sound
        await pg.click('.art-sec:has(h3:text-is("Sound effects")) button'); await pg.wait_for_timeout(250)
        ck('New sound offers 12 kinds and a blank one', await pg.locator('.sheet .kind').count() == 13)
        await pg.click('.sheet .kind[data-kind=laser]'); await pg.wait_for_timeout(250)
        ck('naming it suggests the kind', await pg.locator('.sheet .big-in').input_value() == 'laser')
        n0 = await ev("window.__plays"); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(400)
        ck('the sound is created and opened in the editor', await doc("sounds.laser") is not None and await ev("document.querySelector('#sfxName').textContent") == 'laser' and not await ev("document.querySelector('#sfxEditor').hidden"))
        ck('and played so you hear it straight away', await ev("window.__plays") > n0)
        ck('it is a valid sound', await errors() == [] and await warnings() == [], await errors())
        ck('a laser slides down', (await doc("sounds.laser.f"))[1] < (await doc("sounds.laser.f"))[0])

        # ============================================================ the pitch graph
        await pg.click('#sfxKinds [data-kind=coin]'); await pg.wait_for_timeout(200)
        f0 = await doc("sounds.laser.f")
        ck('a kind chip remakes the sound as that kind (a coin slides up)', f0[1] > f0[0] and await doc("sounds.laser.wave") in ('square', 'triangle'), f0)
        box = await pg.locator('#sfxCanvas').bounding_box()
        g = await ev("(() => { const e = DC2_STUDIO.sfx, P = e.plot(); return { x0: P.x0 + 14, w: P.w - 28, y0: P.y0, h: P.h }; })()")
        def gy(hz): return g['y0'] + (1 - __import__('math').log(hz / 30) / __import__('math').log(9000 / 30)) * g['h']
        u0 = await ev(f"{S}.doc.undos.length")
        await pg.mouse.move(box['x'] + g['x0'] + 5, box['y'] + gy(f0[0])); await pg.mouse.down()
        await pg.mouse.move(box['x'] + g['x0'] + 5, box['y'] + gy(f0[0]) - 40, steps=5); await pg.mouse.move(box['x'] + g['x0'] + 5, box['y'] + gy(f0[0]) - 80, steps=5); await pg.mouse.up(); await pg.wait_for_timeout(250)
        f1 = await doc("sounds.laser.f")
        ck('dragging the left side of the graph up raises the start pitch', f1[0] > f0[0] * 1.3 and f1[1] == f0[1], [f0, f1])
        import math
        semis = 12 * math.log2(f1[0] / 440); ck('and it snaps to a real note', abs(semis - round(semis)) < 0.12, semis)
        ck('the whole drag is one undo step', await ev(f"{S}.doc.undos.length") == u0 + 1)
        await pg.click('#sfxUndo'); await pg.wait_for_timeout(150)
        ck('which undoes', await doc("sounds.laser.f") == f0 and await ev("DC2_STUDIO.sfx.def.f.join()") == ','.join(str(x) for x in f0))
        await pg.click('#sfxRedo'); await pg.wait_for_timeout(100)
        await pg.mouse.move(box['x'] + g['x0'] + g['w'] - 5, box['y'] + gy(f1[1])); await pg.mouse.down(); await pg.mouse.move(box['x'] + g['x0'] + g['w'] - 5, box['y'] + gy(f1[1]) + 60, steps=6); await pg.mouse.up(); await pg.wait_for_timeout(150)
        f2 = await doc("sounds.laser.f")
        ck('the right side sets the end pitch (dragging down lowers it)', f2[1] < f1[1] * 0.8 and f2[0] == f1[0], [f1, f2])
        await ev("window.__plays = 0")
        await pg.mouse.move(box['x'] + g['x0'] + 5, box['y'] + 100); await pg.mouse.down(); await pg.mouse.move(box['x'] + g['x0'] + 5, box['y'] + 60, steps=3); await pg.mouse.up(); await pg.wait_for_timeout(500)
        ck('after a drag the sound plays by itself', await ev("window.__plays") >= 1)
        await pg.click('#sfxControls button:has-text("Play after each change")'); await ev("window.__plays = 0")
        await pg.mouse.move(box['x'] + g['x0'] + 5, box['y'] + 120); await pg.mouse.down(); await pg.mouse.move(box['x'] + g['x0'] + 5, box['y'] + 90, steps=3); await pg.mouse.up(); await pg.wait_for_timeout(500)
        ck('with "Play after each change" off it stays quiet', await ev("window.__plays") == 0)
        n0 = await ev("window.__plays"); await pg.click('#sfxPlay'); await pg.wait_for_timeout(100)
        ck('and ▶ Play still plays', await ev("window.__plays") == n0 + 1)
        await pg.click('#sfxControls button:has-text("Play after each change")')
        ck('the pitch is described in words and notes', 'From' in await pg.locator('.sfx-read').text_content() and 'Hz' in await pg.locator('.sfx-read').text_content(), await pg.locator('.sfx-read').text_content())

        # waves, modes, steps
        await pg.click('#sfxControls [data-wave=sawtooth]'); await pg.wait_for_timeout(120)
        ck('wave: Saw', await doc("sounds.laser.wave") == 'sawtooth' and await pg.locator('#sfxControls [data-wave=sawtooth].on').count() == 1)
        await pg.click('#sfxControls [data-wave=noise]'); await pg.wait_for_timeout(120)
        ck('wave: Noise', await doc("sounds.laser.wave") == 'noise' and await errors() == [])
        await ev(f"{S}.doc.set(['sounds','laser','noise'], true)"); await pg.click('#sfxControls [data-wave=sine]'); await pg.wait_for_timeout(100)
        ck('an old "noise" flag is cleared when you pick a wave (so it cannot override it)', await doc("sounds.laser.noise") is None and await doc("sounds.laser.wave") == 'sine')
        await pg.click('#sfxControls [data-mode=steady]'); await pg.wait_for_timeout(120)
        ck('One pitch: a single value', len(await doc("sounds.laser.f")) == 1 and await pg.locator('#sfxControls [data-mode=steady].on').count() == 1)
        await pg.click('#sfxControls [data-mode=steps]'); await pg.wait_for_timeout(120)
        ck('Steps: three or more', len(await doc("sounds.laser.f")) >= 3 and await pg.locator('#sfxControls .stepper').is_visible())
        await pg.click('#sfxControls .stepper button[aria-label="More steps"]'); await pg.wait_for_timeout(80)
        ck('＋ adds a step', len(await doc("sounds.laser.f")) == 4 and '4 steps' in await pg.locator('#sfxControls .stepper .val').text_content())
        for _ in range(8): await pg.click('#sfxControls .stepper button[aria-label="More steps"]')
        ck('up to eight', len(await doc("sounds.laser.f")) == 8)
        for _ in range(9): await pg.click('#sfxControls .stepper button[aria-label="Fewer steps"]')
        ck('and down to three', len(await doc("sounds.laser.f")) == 3)
        await pg.wait_for_timeout(200)
        before = await doc("sounds.laser.f")
        await pg.mouse.move(box['x'] + g['x0'] + 10, box['y'] + 150); await pg.mouse.down()
        await pg.mouse.move(box['x'] + g['x0'] + g['w'] - 10, box['y'] + 60, steps=24); await pg.mouse.up(); await pg.wait_for_timeout(150)
        after = await doc("sounds.laser.f")
        ck('in Steps, dragging across paints a pitch for each column (a rising contour)', after[0] < after[1] < after[2] and after != before, after)
        await pg.click('#sfxControls [data-mode=slide]'); await pg.wait_for_timeout(100)
        ck('Slide: two values', len(await doc("sounds.laser.f")) == 2)
        # sliders
        await pg.locator('#sfxControls [data-sfx=d]').fill('100'); await pg.wait_for_timeout(80); ck('length slider to the end = 3 seconds', await doc("sounds.laser.d") == 3)
        await pg.locator('#sfxControls [data-sfx=d]').fill('0'); await pg.wait_for_timeout(80); ck('and to the start = 0.02 seconds', await doc("sounds.laser.d") == 0.02)
        await pg.locator('#sfxControls [data-sfx=d]').fill('50'); await pg.wait_for_timeout(80); dm = await doc("sounds.laser.d")
        ck('the middle is the geometric middle of 0.02 s and 3 s (about 0.25 s)', 0.22 < dm < 0.27, dm)
        await pg.locator('#sfxControls [data-sfx=v]').fill('50'); await pg.wait_for_timeout(80); ck('volume 50% along the curve = 0.25', await doc("sounds.laser.v") == 0.25)
        ck('the values are shown', '25%' in await pg.locator('#sfxControls .sfx-ctl:has([data-sfx=v]) output').text_content())
        u0 = await ev(f"{S}.doc.undos.length")
        await pg.wait_for_timeout(1000)
        for v in (30, 40, 60, 70): await pg.locator('#sfxControls [data-sfx=v]').fill(str(v)); await pg.wait_for_timeout(30)
        ck('moving a slider through many values is one undo step', await ev(f"{S}.doc.undos.length") == u0 + 1)
        await pg.click('#sfxControls [data-act=vary]'); await pg.wait_for_timeout(100); fv = await doc("sounds.laser.f")
        ck('Vary changes the pitch a little and keeps the wave and volume', fv != after and await doc("sounds.laser.wave") == 'sine' and await doc("sounds.laser.v") == 0.49)
        await pg.click('#sfxKinds [data-kind=boom]'); await pg.wait_for_timeout(100)
        ck('Boom: noise, long', await doc("sounds.laser.wave") == 'noise' and await doc("sounds.laser.d") >= 0.45)
        a1 = str(await doc("sounds.laser")); await pg.click('#sfxKinds [data-kind=boom]'); await pg.wait_for_timeout(100)
        ck('tapping the kind again gives a different one', str(await doc("sounds.laser")) != a1)
        ck('everything it made is valid', await errors() == [] and await warnings() == [], await errors())

        # menu: rename, copy, delete
        await ev(f"{S}.doc.cart.prefabs[{S}.doc.cart.meta.player].rules.push({{ on: 'button', button: 'x', then: [{{ act: 'sound', id: 'laser' }}] }}); {S}.doc.set(['meta','title'], {S}.doc.cart.meta.title)")
        await pg.click('#sfxMore'); await pg.wait_for_timeout(200); await sheet_btn('Rename'); await pg.fill('.sheet .big-in', 'zap'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(300)
        ck('renaming works, the editor follows, and the rule that plays it is updated', await doc("sounds.zap") is not None and await doc("sounds.laser") is None and await ev("document.querySelector('#sfxName').textContent") == 'zap'
           and await ev(f"JSON.stringify({S}.doc.cart.prefabs[{S}.doc.cart.meta.player].rules).includes('\"id\":\"zap\"')") and await errors() == [], await errors())
        await pg.click('#sfxMore'); await pg.wait_for_timeout(200); await sheet_btn('Make a copy'); await pg.wait_for_timeout(250)
        ck('a copy is made and opened', await ev("Object.keys(DC2_STUDIO.doc.cart.sounds).some(k => k.startsWith('zap') && k !== 'zap')"))
        cp = await ev("document.querySelector('#sfxName').textContent"); ck('the copy is a separate sound', cp != 'zap' and await ev(f"JSON.stringify({S}.doc.cart.sounds['{cp}']) === JSON.stringify({S}.doc.cart.sounds.zap)"), cp)
        await pg.click('#sfxMore'); await pg.wait_for_timeout(200); await sheet_btn('Delete'); await pg.wait_for_timeout(200)
        ck('deleting asks first', await pg.locator('.sheet:has-text("Delete the sound")').count() == 1)
        await sheet_btn('Delete'); await pg.wait_for_timeout(300)
        ck('then removes it and returns to the list', await doc(f"sounds['{cp}']") is None and await ev("document.querySelector('#sfxEditor').hidden") and await pg.locator(f'.sndcard[data-sound="{cp}"]').count() == 0)
        await pg.click('.sndcard[data-sound=zap]'); await pg.wait_for_timeout(250)
        await pg.click('#sfxMore'); await pg.wait_for_timeout(200); await sheet_btn('Delete'); await pg.wait_for_timeout(200)
        ck('a sound that rules use warns how many', 'rule plays it' in await pg.locator('.sheet').inner_text(), await pg.locator('.sheet').inner_text())
        await close_sheets(); await pg.click('#sfxBack'); await pg.wait_for_timeout(150)

        # ============================================================ making a song
        await pg.click('.art-sec:has(h3:text-is("Music")) button'); await pg.wait_for_timeout(250)
        ck('New song offers moods, keys and lengths', await pg.locator('.sheet .chip-btn[data-v]').count() == 7 and await pg.locator('.sheet .keygrid .chip-btn').count() == 12)
        await pg.click('.sheet .chip-btn[data-v=sad]'); await pg.click('.sheet .keygrid [data-key=A]'); await pg.click('.sheet .chip-btn[data-v="8"]'); await pg.wait_for_timeout(100)
        ck('the choices light up', await pg.locator('.sheet .chip-btn[data-v=sad].on').count() == 1 and await pg.locator('.sheet .keygrid [data-key=A].on').count() == 1)
        await pg.click('.sheet button:has-text("Make a song")'); await pg.wait_for_timeout(200)
        ck('naming it suggests the mood', await pg.locator('.sheet .big-in').input_value() == 'sad')
        await pg.keyboard.press('Enter'); await pg.wait_for_timeout(700)
        sg = await doc("music.sad")
        ck('a four-track song is made, 8 bars at the sad tempo', sg is not None and len(sg['tracks']) == 4 and sg['bpm'] == 84 and (await ev("DC2.studio.snd.song.steps(DC2_STUDIO.doc.cart.music.sad)")) == 64)
        ck('and it is valid', await errors() == [] and await warnings() == [], await errors())
        ck('the editor opens and the song starts playing', not await ev("document.querySelector('#musicEditor').hidden") and await ev(f"{A}.songName") == '@editor' and await ev("document.querySelector('#musPlay').textContent") == '■ Stop')
        ck('it knows the key (A minor)', 'A minor' in await pg.locator('#musSettings [data-act=key]').text_content(), await pg.locator('#musSettings [data-act=key]').text_content())
        await pg.click('#musPlay'); await pg.wait_for_timeout(100)
        ck('Stop stops it', await ev(f"{A}.songName") is None and await ev("document.querySelector('#musPlay').textContent") == '▶ Play')
        await pg.click('#musBack'); await pg.wait_for_timeout(200)
        await pg.click('.art-sec:has(h3:text-is("Music")) button'); await pg.wait_for_timeout(200); await pg.click('.sheet button:has-text("Empty song")'); await pg.wait_for_timeout(200)
        await pg.fill('.sheet .big-in', 'mine'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(500)
        ck('an empty song is one track of 32 rests', await ev("DC2.studio.snd.song.steps(DC2_STUDIO.doc.cart.music.mine)") == 32 and not await ev("DC2.studio.snd.track.parse(DC2_STUDIO.doc.cart.music.mine.tracks[0].notes).events.length"), await doc("music.mine"))
        await pg.click('#musPlay'); await pg.wait_for_timeout(100)

        # ============================================================ the piano roll
        async def cell(step, note=None, hz=None):
            return await ev("""(a) => { const e = DC2_STUDIO.songEd, GW = 46, RH = 22, rows = e.rows(); const ri = a.hz != null ? rows.findIndex(r => r.drum && r.hz === a.hz) : rows.findIndex(r => r.m === a.note); if (ri < 0) return null;
              e.holdFollow(); e.cw = 30; e.ox = Math.max(0, Math.min(a.step * e.cw - 100, e.steps * e.cw - (e.cssW - GW))); e.oy = Math.max(0, Math.min(ri * e.rh - 120, rows.length * e.rh - (e.cssH - RH))); e.redraw();
              const r = e.cv.getBoundingClientRect(); return { x: r.left + GW + (a.step + 0.5) * e.cw - e.ox, y: r.top + RH + (ri + 0.5) * e.rh - e.oy, cw: e.cw, rh: e.rh }; }""", {'step': step, 'note': note, 'hz': hz})
        async def tap(step, note=None, hz=None):
            c = await cell(step, note, hz); await pg.mouse.move(c['x'], c['y']); await pg.mouse.down(); await pg.mouse.up(); await pg.wait_for_timeout(60)
        async def events(ti=0): return await ev("(ti) => DC2.studio.snd.track.parse(DC2_STUDIO.doc.cart.music['" + 'mine' + "'].tracks[ti].notes).events.map(e => [e.s, e.l, e.tok])", ti)
        async def notes(ti=0): return await doc(f"music.mine.tracks[{ti}].notes")
        await pg.click('#musTools [data-len="1"]')
        u0 = await ev(f"{S}.doc.undos.length")
        await tap(0, 72)
        ck('tapping an empty square puts a note there (C5 at step 0)', await events() == [[0, 1, 'C5']], await events())
        ck('as one undo step', await ev(f"{S}.doc.undos.length") == u0 + 1)
        ck('and plays the pitch so you hear what you placed', ['square', 523] in await ev("window.__blips"), await ev("window.__blips.slice(-3)"))
        await tap(4, 76); await tap(8, 79)
        ck('more notes: E5 at 4, G5 at 8', await events() == [[0, 1, 'C5'], [4, 1, 'E5'], [8, 1, 'G5']])
        ck('the song text has bar lines every 8 steps and is valid', '|' in await notes() and (await notes()).split(' | ')[0].split(' ').__len__() == 8 and await errors() == [], await notes())
        await tap(4, 76); ck('tapping a note removes it', await events() == [[0, 1, 'C5'], [8, 1, 'G5']])
        c = await cell(12, 74); await pg.mouse.move(c['x'], c['y']); await pg.mouse.down(); await pg.mouse.move(c['x'] + c['cw'] * 3, c['y'], steps=6); await pg.mouse.up(); await pg.wait_for_timeout(100)
        ck('dragging along makes a longer note (4 steps)', (await events())[-1] == [12, 4, 'D5'], await events())
        u0 = await ev(f"{S}.doc.undos.length"); c = await cell(8, 79); await pg.mouse.move(c['x'], c['y']); await pg.mouse.down(); await pg.mouse.move(c['x'] + c['cw'] * 2, c['y'], steps=5); await pg.mouse.up(); await pg.wait_for_timeout(100)
        ck('dragging an existing note lengthens it, instead of removing it', (await events())[1] == [8, 3, 'G5'] and await ev(f"{S}.doc.undos.length") == u0 + 1, await events())
        c = await cell(9, 79); await pg.mouse.move(c['x'], c['y']); await pg.mouse.down(); await pg.mouse.move(c['x'] - c['cw'], c['y'], steps=4); await pg.mouse.up(); await pg.wait_for_timeout(100)
        ck('and dragging back shortens it', (await events())[1][1] <= 2, await events())
        await tap(10, 79); await pg.click('#musTools [data-len="4"]'); await tap(16, 77)
        ck('the length chips set how long a tapped note is (4)', (await events())[-1] == [16, 4, 'F5'], await events())
        await pg.click('#musTools [data-len="1"]'); await tap(18, 71)
        ck('a note placed inside a long one cuts it short', [e for e in await events() if e[0] == 16] == [[16, 2, 'F5']] and [18, 1, 'B4'] in await events(), await events())
        await pg.click('#musTools [data-tool=erase]'); c1 = await cell(0, 72); c2 = await cell(0, 72)
        await tap(0, 72); ck('the Erase tool removes a note with a touch', [0, 1, 'C5'] not in await events())
        e0 = len(await events()); ck('and there are still others', e0 >= 3)
        await pg.click('#musTools [data-tool=draw]')
        # ---- scroll, zoom
        await pg.click('#musTools [data-tool=pan]'); c = await ev("(() => { const r = DC2_STUDIO.songEd.cv.getBoundingClientRect(); return { x: r.left + 200, y: r.top + 200 }; })()")
        await ev("DC2_STUDIO.songEd.ox = 0; DC2_STUDIO.songEd.oy = 100"); await pg.mouse.move(c['x'], c['y']); await pg.mouse.down(); await pg.mouse.move(c['x'] - 90, c['y'] + 30, steps=5); await pg.mouse.up()
        ox, oy = await ev("[DC2_STUDIO.songEd.ox, DC2_STUDIO.songEd.oy]")
        ck('the Move tool scrolls the roll by dragging', 80 < ox < 100 and 60 < oy < 80, [ox, oy])
        n_before = len(await events()); await pg.mouse.move(c['x'], c['y']); await pg.mouse.down(); await pg.mouse.up(); ck('and does not change any notes', len(await events()) == n_before)
        await pg.click('#musTools [data-tool=draw]')
        cw0 = await ev("DC2_STUDIO.songEd.cw"); await pg.click('#rollZoomIn'); cw1 = await ev("DC2_STUDIO.songEd.cw"); await pg.click('#rollZoomOut'); await pg.click('#rollZoomOut'); cw2 = await ev("DC2_STUDIO.songEd.cw")
        ck('zoom ＋ and － change the step width', cw1 > cw0 > cw2, [cw0, cw1, cw2])
        await pg.click('#rollFit'); ck('⤢ shows the whole song', await ev("(() => { const e = DC2_STUDIO.songEd; return e.steps * e.cw <= e.cssW - 46 + 1; })()"))
        await ev("DC2_STUDIO.songEd.cw = 30; DC2_STUDIO.songEd.ox = 0")
        await pg.mouse.move(c['x'], c['y']); await pg.mouse.wheel(0, 120); await pg.wait_for_timeout(80)
        ck('the mouse wheel scrolls up and down', await ev("DC2_STUDIO.songEd.oy") > 0)
        # ---- gutter, ruler
        n0 = len(await ev("window.__blips")); g0 = await ev("(() => { const e = DC2_STUDIO.songEd, r = e.cv.getBoundingClientRect(); return { x: r.left + 20, y: r.top + 22 + (Math.floor(e.oy / e.rh) + 3) * e.rh + 4 - e.oy }; })()")
        await pg.mouse.move(g0['x'], g0['y']); await pg.mouse.down(); await pg.mouse.up(); await pg.wait_for_timeout(60)
        ck('tapping the piano keys on the left plays that note', len(await ev("window.__blips")) == n0 + 1)
        ck('and does not add a note', len(await events()) == n_before)
        await pg.click('#musPlay'); await pg.wait_for_timeout(100)
        ck('▶ plays the song being edited', await ev(f"{A}.songName") == '@editor' and await ev("document.querySelector('#musPlay').textContent") == '■ Stop')
        pos1 = await ev(f"{A}.songPos()"); await pg.wait_for_timeout(700); pos2 = await ev(f"{A}.songPos()")
        ck('the playhead moves along the song', pos1 >= 0 and abs(pos2 - pos1) > 0.5, [pos1, pos2])
        ck('and the picture follows it', 0 <= await ev("DC2_STUDIO.songEd.pos") < 32)
        ck('with sound on the music channel (the first note is two seconds in)', await peak('music', 3200) > 0.005)
        timer = await ev(f"{A}.timer"); sp = await ev(f"{A}.song.pos")
        await tap(20, 74)
        ck('a note added while it plays is heard without restarting the song', await ev(f"{A}.song.tracks[0].at[20] !== undefined") and await ev(f"{A}.timer") == timer, await ev(f"Object.keys({A}.song.tracks[0].at)"))
        await ev(f"{S}.doc.set(['music','mine','tracks',0,'v'], 0.2)"); await pg.wait_for_timeout(60)
        ck('a volume change is heard immediately too', abs(await ev(f"{A}.song.tracks[0].v") - 0.2) < 1e-6)
        c = await cell(0, 72); await ev("DC2_STUDIO.songEd.holdFollow(); DC2_STUDIO.songEd.ox = 0; DC2_STUDIO.songEd.redraw()"); r = await ev("DC2_STUDIO.songEd.cv.getBoundingClientRect().left + 46 + 6 * 30 + 10")
        ry = await ev("DC2_STUDIO.songEd.cv.getBoundingClientRect().top + 10"); await pg.mouse.move(r, ry); await pg.mouse.down(); await pg.mouse.up(); await pg.wait_for_timeout(150)
        ck('tapping the ruler sets where playing starts, and restarts there', await ev("DC2_STUDIO.songEd.start") == 6 and await ev(f"{A}.song.p0") == 6, await ev("DC2_STUDIO.songEd.start"))
        await pg.click('#musPlay'); await pg.wait_for_timeout(100); ck('stopped', await ev(f"{A}.songName") is None)
        await ev("DC2_STUDIO.songEd.start = 0")

        # ---- key and scale
        await pg.click('#musSettings [data-act=key]'); await pg.wait_for_timeout(200)
        await pg.click('.sheet .keygrid [data-key=C]'); await pg.click('.sheet [data-scale=major]'); await pg.wait_for_timeout(100)
        rows_all = await ev("DC2_STUDIO.songEd.rows().length")
        await pg.click('.sheet [data-act=lock]'); await pg.wait_for_timeout(100)
        rows_lock = await ev("DC2_STUDIO.songEd.rows().map(r => r.label)")
        ck('"Only show notes in the key" hides the black keys (C major)', len(rows_lock) < rows_all and not any('#' in x for x in rows_lock), rows_lock)
        ck('the key button says so', '🔒' in await pg.locator('#musSettings [data-act=key]').text_content())
        await pg.click('.sheet [data-scale=chromatic]'); await pg.wait_for_timeout(80)
        ck('with "all notes" the lock changes nothing', await ev("DC2_STUDIO.songEd.rows().length") == rows_all)
        await pg.click('.sheet [data-scale=minor]'); await pg.click('.sheet .keygrid [data-key=A]'); await pg.wait_for_timeout(80)
        await pg.click('.sheet [data-act=lock]'); await pg.click('.sheet [data-act=detect]'); await pg.wait_for_timeout(100)
        ck('"Work it out from my notes" picks the key from what you wrote', await ev("DC2_STUDIO.songEd.key.scale") in ('major', 'minor'), await ev("DC2_STUDIO.songEd.key"))
        await close_sheets()
        ck('the key is only a view setting: it is not in the song', 'key' not in await ev("Object.keys(DC2_STUDIO.doc.cart.music.mine).join(' ')"))

        # ---- tempo, length, steps per beat
        bpm0 = await doc("music.mine.bpm")
        await pg.click('#musSettings .stepper:first-child button[aria-label=more]'); await pg.wait_for_timeout(60)
        ck('tempo ＋ adds 4 bpm', await doc("music.mine.bpm") == bpm0 + 4)
        await pg.click('#musSettings [data-act=bpm]'); await pg.wait_for_timeout(200); await pg.fill('.sheet .big-in', '150'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(200)
        ck('tapping the tempo lets you type one', await doc("music.mine.bpm") == 150)
        await pg.click('#musSettings [data-act=bpm]'); await pg.wait_for_timeout(200); await pg.fill('.sheet .big-in', '999'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(200)
        ck('a silly tempo is refused', await doc("music.mine.bpm") == 150)
        await close_sheets()
        await pg.click('#musSettings .stepper:nth-child(2) button[aria-label=more]'); await pg.wait_for_timeout(150)
        ck('Length ＋ adds a bar to every track', await ev("DC2.studio.snd.song.steps(DC2_STUDIO.doc.cart.music.mine)") == 40 and '5 bars' in await pg.locator('#musSettings [data-act=length]').text_content())
        await pg.click('#musSettings .stepper:nth-child(2) button[aria-label=less]'); await pg.click('#musSettings .stepper:nth-child(2) button[aria-label=less]'); await pg.wait_for_timeout(150)
        ck('－ removes bars; notes past the end go', await ev("DC2.studio.snd.song.steps(DC2_STUDIO.doc.cart.music.mine)") == 24 and all(e[0] < 24 for e in await events()))
        await pg.click('#musSettings .stepper:nth-child(2) button[aria-label=more]'); await pg.click('#musSettings .stepper:nth-child(2) button[aria-label=more]'); await pg.wait_for_timeout(150)
        step0 = await ev("DC.Audio.buildSong(DC2_STUDIO.doc.cart.music.mine).step")
        await pg.click('#musMore'); await pg.wait_for_timeout(150); await sheet_btn('Song settings'); await pg.click('.sheet [data-div="4"]'); await pg.wait_for_timeout(150)
        step1 = await ev("DC.Audio.buildSong(DC2_STUDIO.doc.cart.music.mine).step")
        ck('more steps per beat keeps the sound the same (tempo adjusts)', await doc("music.mine.div") == 4 and await doc("music.mine.bpm") == 75 and abs(step0 - step1) < 1e-9, [step0, step1, await doc("music.mine.bpm")])
        await pg.click('.sheet [data-div="2"]'); await pg.wait_for_timeout(100)
        await pg.click('.sheet [data-loop=off]'); await pg.wait_for_timeout(100)
        ck('"Stop" at the end makes the song play once', await doc("music.mine.loop") is False and await errors() == [])
        await pg.click('.sheet [data-loop=on]'); await close_sheets()

        # ---- tracks
        await pg.click('#musTracks [data-act=add-track]'); await pg.wait_for_timeout(150)
        ck('Add a track offers the kinds', await pg.locator('.sheet .menu-item').count() == 5)
        await sheet_btn('Drums'); await pg.wait_for_timeout(200)
        ck('a drum track is added and selected', await ev("DC2_STUDIO.songEd.ti") == 1 and await doc("music.mine.tracks[1].wave") == 'noise' and await pg.locator('#musTracks .trackchip').count() == 2)
        lanes = await ev("DC2_STUDIO.songEd.rows().map(r => r.label)")
        ck('drum tracks show lanes instead of piano keys', lanes == ['Hat', 'Snare', 'Tom', 'Kick'], lanes)
        await tap(0, hz=300); await tap(2, hz=9000); await tap(4, hz=3500)
        ck('drum notes are written as pitches the engine reads', await events(1) == [[0, 1, '300'], [2, 1, '9000'], [4, 1, '3500']], await events(1))
        ck('and are valid', await errors() == [] and await warnings() == [], await warnings())
        ck('tapping a drum lane plays noise', ['noise', 300] in await ev("window.__blips"))
        await pg.click('#musTracks [data-track="0"]'); await pg.wait_for_timeout(100)
        ck('selecting the other track brings its notes back', await ev("DC2_STUDIO.songEd.rows().some(r => r.m)") and len(await events(0)) >= 3)
        await pg.click('#musStrip [data-act=mute]'); await pg.wait_for_timeout(80)
        ck('M mutes a track while you work (not saved)', await ev("DC2_STUDIO.songEd.mute.size") == 1 and 'mute' not in str(await doc("music.mine")))
        await pg.click('#musPlay'); await pg.wait_for_timeout(200)
        ck('and it is left out of what plays', await ev(f"{A}.song.tracks.length") == 1)
        await pg.click('#musStrip [data-act=mute]'); await pg.wait_for_timeout(80)
        ck('un-muting puts it back, live', await ev(f"{A}.song.tracks.length") == 2)
        await pg.click('#musStrip [data-act=solo]'); await pg.wait_for_timeout(80)
        ck('S plays only that track', await ev(f"{A}.song.tracks.length") == 1 and await ev(f"{A}.song.tracks[0].wave") == 'square')
        await pg.click('#musStrip [data-act=solo]'); await pg.click('#musPlay'); await pg.wait_for_timeout(100)
        await pg.locator('#musStrip [data-mus=vol]').fill('70'); await pg.wait_for_timeout(80)
        ck('the track volume slider sets its level on the curve (70% along = 0.49)', await doc("music.mine.tracks[0].v") == 0.49)
        await pg.click('#musStrip [data-act=wave]'); await pg.wait_for_timeout(150); await pg.click('.sheet [data-wave=triangle]'); await pg.wait_for_timeout(150)
        ck('the instrument can be changed', await doc("music.mine.tracks[0].wave") == 'triangle' and '1 Triangle' in await pg.locator('#musTracks [data-track="0"]').text_content())
        await pg.click('#musStrip [data-act=track-menu]'); await pg.wait_for_timeout(150); before = await events(0); await sheet_btn('Up an octave'); await pg.wait_for_timeout(150)
        after = await events(0); ck('Up an octave moves every note by 12', [e[2] for e in after] == [x[2][:-1] + str(int(x[2][-1]) + 1) for x in before] and [e[:2] for e in after] == [e[:2] for e in before], [before[:2], after[:2]])
        await pg.click('#musStrip [data-act=track-menu]'); await pg.wait_for_timeout(150); await sheet_btn('Make up notes'); await pg.wait_for_timeout(300)
        mk = await events(0); ck('"Make up notes" fills the track', len(mk) >= 6 and await errors() == [], len(mk))
        ck('and starts playing so you can hear it', await ev(f"{A}.songName") == '@editor')
        await pg.click('#musPlay'); await pg.wait_for_timeout(100)
        await pg.click('#musStrip [data-act=track-menu]'); await pg.wait_for_timeout(150); await sheet_btn('Clear every note'); await pg.wait_for_timeout(150)
        ck('Clear every note', await events(0) == [] and (await notes(0)).count('.') == 40, await notes(0))
        await pg.click('#musUndo'); await pg.wait_for_timeout(150); ck('and Undo brings them back', len(await events(0)) >= 6)
        await pg.click('#musStrip [data-act=track-menu]'); await pg.wait_for_timeout(150); await sheet_btn('Make a copy of this track'); await pg.wait_for_timeout(200)
        ck('a track can be copied', await pg.locator('#musTracks .trackchip').count() == 3 and await events(1) == await events(0))
        await pg.click('#musStrip [data-act=track-menu]'); await pg.wait_for_timeout(150); await sheet_btn('Delete this track'); await pg.wait_for_timeout(150); await sheet_btn('Delete'); await pg.wait_for_timeout(250)
        ck('and deleted (after asking)', await pg.locator('#musTracks .trackchip').count() == 2 and await errors() == [])

        # ---- the song's own menu
        await pg.click('#musMore'); await pg.wait_for_timeout(150); await sheet_btn('Play this song in a level'); await pg.wait_for_timeout(200)
        ck('the level sheet lists the levels', await pg.locator('.sheet [data-level]').count() == 2)
        await pg.locator('.sheet [data-level=cave] button').click(); await pg.wait_for_timeout(250)
        ck('a level can be set to play this song', await doc("scenes.cave.music") == 'mine')
        await pg.locator('.sheet [data-level=cave] button').click(); await pg.wait_for_timeout(250)
        ck('and set back (the song is removed from it)', await doc("scenes.cave.music") is None)
        await pg.locator('.sheet [data-level=cave] button').click(); await pg.wait_for_timeout(200); await close_sheets()
        await pg.click('#musMore'); await pg.wait_for_timeout(150); await sheet_btn('Rename'); await pg.fill('.sheet .big-in', 'cavern'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(300)
        ck('renaming a song updates the level that plays it', await doc("music.cavern") is not None and await doc("scenes.cave.music") == 'cavern' and await ev("document.querySelector('#musName').textContent") == 'cavern' and await errors() == [])
        await pg.click('#musMore'); await pg.wait_for_timeout(150); await sheet_btn('Delete'); await pg.wait_for_timeout(150)
        ck('deleting says which levels will lose their music', 'cave will have no music' in await pg.locator('.sheet').inner_text())
        await pg.click('.sheet button:has-text("Delete") >> nth=-1'); await pg.wait_for_timeout(300)
        ck('then it is gone and the level is valid without music', await doc("music.cavern") is None and await doc("scenes.cave.music") is None and await errors() == [] and await ev("document.querySelector('#musicEditor').hidden"))
        await pg.click('#tabs [data-tab=game]'); await pg.wait_for_timeout(200)
        await pg.locator('#gameBody .lvl-row:has(b:text-is("cave")) button:has-text("Settings")').click(); await pg.wait_for_timeout(300)
        ck('the level settings have a Music picker listing the songs', await pg.locator('.sheet select[data-level-music=cave] option').count() == 1 + len(await ev("Object.keys(DC2_STUDIO.doc.cart.music)")))
        await pg.select_option('.sheet select[data-level-music=cave]', 'sad'); await pg.wait_for_timeout(250)
        ck('picking one sets it for the level', await doc("scenes.cave.music") == 'sad' and await errors() == [])
        await pg.select_option('.sheet select[data-level-music=cave]', ''); await pg.wait_for_timeout(250)
        ck('and "(no music)" clears it', await doc("scenes.cave.music") is None)
        await close_sheets()

        # ---- leaving the editor stops the music
        await pg.click('#tabs [data-tab=sound]'); await pg.wait_for_timeout(200); await pg.click('.sndcard[data-song=sad]'); await pg.wait_for_timeout(500)
        ck('opening a song from the list opens the roll (and prepares a song written as one track)', not await ev("document.querySelector('#musicEditor').hidden"))
        await pg.click('#musPlay'); await pg.wait_for_timeout(200); ck('playing', await ev(f"{A}.songName") == '@editor')
        await pg.click('#musBack'); await pg.wait_for_timeout(200)
        ck('going back stops the music', await ev(f"{A}.songName") is None and await ev("document.querySelector('#musicEditor').hidden"))
        await ev(f"{S}.doc.set(['music','old'], {{ bpm: 100, wave: 'square', v: 0.08, notes: 'C4 D4 E4 F4 G4 A4 B4 C5' }})"); await pg.wait_for_timeout(200)
        sound_before = await ev("JSON.stringify(DC.Audio.buildSong(DC2_STUDIO.doc.cart.music.old).tracks[0].at)")
        await pg.click('.sndcard[data-song=old]'); await pg.wait_for_timeout(500)
        ck('a song written as a single track is converted to a track list when opened, and sounds the same', await ev("Array.isArray(DC2_STUDIO.doc.cart.music.old.tracks)") and await ev("JSON.stringify(DC.Audio.buildSong(DC2_STUDIO.doc.cart.music.old).tracks[0].at)") == sound_before)
        await pg.click('#musBack'); await pg.wait_for_timeout(150)
        ck('the whole project validates', await errors() == [], await errors())
        print('page errors:', errs or 'none'); ck('no page errors', not errs, errs)
        print(f'{P} passed, {F} failed'); await b.close()
asyncio.run(main())
