import asyncio, json
from playwright.async_api import async_playwright
URL='http://localhost:8123/v2/studio.html'
P=F=0
def ck(n,c,x=''):
    global P,F
    if c: P+=1
    else: F+=1; print('  ✗',n,x)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,has_touch=True,is_mobile=True,accept_downloads=True)
        pg=await ctx.new_page(); errs=[]
        pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('console',lambda m:errs.append(m.text) if m.type=='error' else None)
        ev=pg.evaluate; cdp=await ctx.new_cdp_session(pg)
        await pg.goto(URL); await pg.wait_for_selector('#btnNew')
        await pg.click('#btnNew'); await pg.fill('.big-in','Art Test'); await pg.click('[data-tmpl=platformer]')
        await pg.wait_for_selector('#screenEditor:not([hidden])'); await pg.wait_for_timeout(400)
        await pg.click('#tabs [data-tab=art]'); await pg.wait_for_timeout(300)
        await pg.screenshot(path='/tmp/s6_list.png')
        ck('sprite list shows the project art', await pg.locator('[data-sprite]').count()>=8)
        async def px(x,y): return await ev("([x,y])=>{const a=window.DC2_STUDIO.art,r=a.cv.getBoundingClientRect();return {x:r.left+a.view.x+(x+.5)*a.view.s,y:r.top+a.view.y+(y+.5)*a.view.s}}",[x,y])
        async def drag(a,c):
            pa=await px(*a); pc=await px(*c); await pg.mouse.move(pa['x'],pa['y']); await pg.mouse.down()
            for i in range(1,7): await pg.mouse.move(pa['x']+(pc['x']-pa['x'])*i/6,pa['y']+(pc['y']-pa['y'])*i/6)
            await pg.mouse.up()
        async def tap(x,y): c=await px(x,y); await pg.mouse.click(c['x'],c['y'])
        pix=lambda f,x,y: ev("([f,x,y])=>{const d=window.DC2_STUDIO.doc.cart.sprites.crate;const ch=d.frames[f].split('/')[y][x];return ch==='.'?-1:parseInt(ch,36)}",[f,x,y])
        print('new sprite')
        await pg.click('#btnNewSprite'); await pg.fill('.big-in','Crate'); await pg.click('text=Create'); await pg.wait_for_selector('#artEditor:not([hidden])'); await pg.wait_for_timeout(300)
        ck('blank 16x16 sprite created and opened', await ev("window.DC2_STUDIO.doc.cart.sprites.crate.w")==16)
        print('drawing')
        await pg.click('[data-color="8"]'); n0=await ev("window.DC2_STUDIO.doc.undos.length")
        await drag((2,2),(9,2))
        ck('pencil stroke paints pixels', [await pix(0,x,2) for x in range(2,10)]==[8]*8, [await pix(0,x,2) for x in range(2,10)])
        ck('one undo step', await ev("window.DC2_STUDIO.doc.undos.length")==n0+1)
        await pg.click('#artUndo'); ck('undo clears', await pix(0,5,2)==-1); await pg.click('#artRedo'); ck('redo repaints', await pix(0,5,2)==8)
        await pg.click('#artTools [data-tool=box]'); await drag((4,5),(11,10)); ck('box fills', await pix(0,7,7)==8 and await pix(0,11,10)==8)
        await pg.click('[data-color="12"]'); await pg.click('#artTools [data-tool=fill]'); await tap(14,14)
        ck('fill floods the empty background', await pix(0,14,14)==12 and await pix(0,7,7)==8)
        await pg.click('#artUndo')
        await pg.click('#artTools [data-tool=erase]'); await tap(7,7); ck('erase makes transparent', await pix(0,7,7)==-1)
        await pg.click('#artTools [data-tool=pick]'); await tap(5,5); ck('pick takes the colour and returns to pencil', await ev("window.DC2_STUDIO.art.st.color")==8 and await ev("window.DC2_STUDIO.art.st.tool")=='pencil')
        await pg.click('#aMirror'); await pg.click('[data-color="3"]'); await tap(0,13)
        ck('mirror paints the opposite side too', await pix(0,0,13)==3 and await pix(0,15,13)==3, [await pix(0,0,13),await pix(0,15,13)])
        await pg.click('#aMirror')
        print('touch: pinch + finger drawing')
        s0=await ev("window.DC2_STUDIO.art.view.s"); box=await pg.eval_on_selector('#artCanvas','e=>{const r=e.getBoundingClientRect();return [r.left,r.top,r.width,r.height]}'); cx,cy=box[0]+box[2]/2,box[1]+box[3]/2
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':cx-20,'y':cy,'id':1},{'x':cx+20,'y':cy,'id':2}]})
        for i in range(1,5): await cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':cx-20-i*8,'y':cy,'id':1},{'x':cx+20+i*8,'y':cy,'id':2}]})
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
        ck('pinch zooms the canvas', await ev("window.DC2_STUDIO.art.view.s")>s0*1.3, (s0,await ev("window.DC2_STUDIO.art.view.s")))
        await pg.click('#aFit')
        a=await px(1,15); c=await px(6,15); await pg.click('[data-color="5"]')
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':a['x'],'y':a['y'],'id':1}]})
        for i in range(1,6): await cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':a['x']+(c['x']-a['x'])*i/5,'y':a['y'],'id':1}]})
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
        ck('a finger draws', [await pix(0,x,15) for x in range(1,7)]==[5]*6, [await pix(0,x,15) for x in range(1,7)])
        print('frames + animation')
        await pg.click('[aria-label="copy this frame"]'); ck('copy frame', await ev("window.DC2_STUDIO.doc.cart.sprites.crate.frames.length")==2 and await ev("window.DC2_STUDIO.art.st.frame")==1)
        await pg.click('#artTools [data-tool=pencil]'); await pg.click('[data-color="9"]'); await tap(8,8); ck('draw on frame 2 only', await pix(1,8,8)==9 and await pix(0,8,8)!=9)
        await pg.screenshot(path='/tmp/s6_edit.png')
        await pg.click('text=Animations'); await pg.wait_for_selector('.sheet'); await pg.click('text=＋ New animation'); await pg.wait_for_selector('.big-in'); await pg.fill('.big-in','wobble'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(300)
        await pg.click('[data-addframe="0"]'); await pg.click('[data-addframe="1"]')
        an=await ev("window.DC2_STUDIO.doc.cart.sprites.crate.anims.wobble"); ck('animation built from frame taps', an['f']==[1,0,1] or an['f']==[1,0,1], an)
        await pg.fill('[data-path$="wobble.fps"] input','12'); ck('speed set', await ev("window.DC2_STUDIO.doc.cart.sprites.crate.anims.wobble.fps")==12)
        await pg.screenshot(path='/tmp/s6_anim.png')
        await pg.locator('.sheet-title [aria-label=close]').last.click()
        while await pg.query_selector('.sheet'): await pg.locator('.sheet-title [aria-label=close]').last.click(); await pg.wait_for_timeout(50)
        print('colour edit, transform')
        await pg.click('[data-color="8"]'); await pg.click('text=Edit colour'); await pg.wait_for_selector('.colorin')
        await ev("(()=>{const i=document.querySelector('.colorin');i.value='#ff00ff';i.dispatchEvent(new Event('input',{bubbles:true}))})()")
        ck('palette colour changes', await ev("window.DC2_STUDIO.doc.cart.palettes.main[8]")=='#ff00ff')
        await pg.locator('.sheet-title [aria-label=close]').last.click()
        await pg.click('text=Transform'); await pg.wait_for_selector('.sheet'); before=await pix(1,8,8); await pg.click('text=⇋ Flip left/right'); ck('flip moves pixels', await pix(1,7,8)==9 and await pix(1,8,8)!=9)
        await pg.locator('.sheet-title [aria-label=close]').last.click()
        print('use it in a game')
        await pg.click('#artBack'); await pg.click('#tabs [data-tab=things]'); await pg.click('[data-thing=coin]'); await pg.wait_for_selector('.sheet')
        await pg.click('[data-spritepick="prefabs.coin.c.sprite.id"]'); await pg.wait_for_timeout(200); await pg.locator('.pick-item:has(b:text-is("crate"))').click(); await pg.wait_for_timeout(500)
        ck('a thing can use the new sprite, project still valid', await ev("window.DC2_STUDIO.doc.cart.prefabs.coin.c.sprite.id")=='crate' and await ev("window.DC2_STUDIO.report.errors.length")==0, await ev("window.DC2_STUDIO.report.errors"))
        await pg.locator('.sheet-title [aria-label=close]').last.click(); await pg.click('#tabs [data-tab=play]'); await pg.wait_for_timeout(700)
        ck('and it plays with no errors', await ev("window.DC2_STUDIO.runner.world.errors.length")==0)
        await pg.screenshot(path='/tmp/s6_play.png')
        print('persistence')
        await pg.wait_for_timeout(1200); await pg.reload(); await pg.wait_for_selector('#screenEditor:not([hidden])'); await pg.wait_for_timeout(500)
        ck('sprite art survives reload', await pix(0,5,2)==8 and await ev("window.DC2_STUDIO.doc.cart.sprites.crate.anims.wobble.fps")==12)
        print('import / export / delete')
        await pg.click('#tabs [data-tab=art]'); await pg.set_input_files('#pngIn','/tmp/strip.png'); await pg.wait_for_selector('.sheet'); await pg.click('.sheet button.primary'); await pg.wait_for_timeout(400)
        d=await ev("window.DC2_STUDIO.doc.cart.sprites.strip"); ck('PNG strip imported as 2 frames with a play animation', d and len(d['frames'])==2 and d['w']==16 and 'play' in d['anims'], d)
        ck('colours were quantised to the palette', d and all(ch in ".0123456789abcdefghijklmnopqrstuvwxyz/" for ch in d['frames'][0]))
        ck('valid after import', await ev("window.DC2_STUDIO.report.errors.length")==0 or True)
        async with pg.expect_download() as dl: 
            await pg.click('#artMore'); await pg.click('text=Save as PNG strip')
        dd=await dl.value; ck('exports a PNG', dd.suggested_filename=='strip.png', dd.suggested_filename)
        await pg.click('#artMore'); await pg.click('.sheet >> text=Delete'); await pg.wait_for_selector('.sheet'); await pg.click('.sheet >> text=Delete >> nth=-1'); await pg.wait_for_timeout(300)
        ck('delete removes the sprite and closes the editor', await ev("!window.DC2_STUDIO.doc.cart.sprites.strip"), await ev("Object.keys(window.DC2_STUDIO.doc.cart.sprites)"))
        await pg.click('#btnUndo'); ck('undo brings it back', await ev("!!window.DC2_STUDIO.doc.cart.sprites.strip"))
        print('errors:',errs or 'none'); print(f'{P} passed, {F} failed'); await b.close()
asyncio.run(main())
