import asyncio, json
from playwright.async_api import async_playwright
URL='http://localhost:8123/v2/studio.html'
P=F=0
def ck(name, cond, extra=''):
    global P,F
    if cond: P+=1
    else: F+=1; print('  ✗', name, extra)
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width':390,'height':844}, device_scale_factor=2, has_touch=True, is_mobile=True, accept_downloads=True)
        pg = await ctx.new_page(); errs=[]
        pg.on('pageerror', lambda e: errs.append('PAGEERR '+str(e)))
        pg.on('console', lambda m: errs.append('CONSOLE '+m.text) if m.type=='error' else None)
        ev = pg.evaluate
        await pg.goto(URL); await pg.wait_for_selector('#btnNew')
        await pg.click('#btnNew'); await pg.fill('.big-in','UI Test'); await pg.click('[data-tmpl=platformer]')
        await pg.wait_for_selector('#screenEditor:not([hidden])'); await pg.wait_for_timeout(500)
        cdp = await ctx.new_cdp_session(pg)

        async def cell(x,y):
            return await ev("""([x,y])=>{const a=window.DC2_STUDIO,mv=a.mv,r=mv.cv.getBoundingClientRect(),ts=mv.ts;return {x:r.left+mv.view.x+(x+.5)*ts*mv.view.s,y:r.top+mv.view.y+(y+.5)*ts*mv.view.s}}""",[x,y])
        async def drag(a,c,steps=8):
            pa=await cell(*a); pc=await cell(*c)
            await pg.mouse.move(pa['x'],pa['y']); await pg.mouse.down()
            for i in range(1,steps+1): await pg.mouse.move(pa['x']+(pc['x']-pa['x'])*i/steps, pa['y']+(pc['y']-pa['y'])*i/steps)
            await pg.mouse.up()
        async def tap(x,y):
            c=await cell(x,y); await pg.mouse.click(c['x'],c['y'])
        tileAt = lambda li,x,y: ev("([li,x,y])=>parseInt(window.DC2_STUDIO.doc.cart.maps.level1.layers[li].rows[y].substr(x*2,2),36)",[li,x,y])
        undos = lambda: ev("window.DC2_STUDIO.doc.undos.length")

        print('A. draw tool')
        n0=await undos()
        await drag((3,2),(8,2))
        row=[await tileAt(0,x,2) for x in range(3,9)]
        ck('stroke paints 6 cells', row==[1]*6, row)
        ck('stroke is one undo step', await undos()==n0+1, await undos()-n0)
        await pg.click('#btnUndo'); ck('undo button clears the stroke', [await tileAt(0,x,2) for x in range(3,9)]==[0]*6)
        await pg.click('#btnRedo'); ck('redo button repaints', await tileAt(0,5,2)==1)
        await pg.click('#btnUndo')

        print('B. box + fill + pick')
        await pg.click('[data-tool=rect]'); await drag((3,3),(6,5))
        cnt=sum([await tileAt(0,x,y)==1 for x in range(3,7) for y in range(3,6)]); ck('box fills 12 cells', cnt==12, cnt)
        await pg.click('#btnUndo'); ck('box undone', await tileAt(0,4,4)==0)
        await pg.click('[data-tool=fill]'); await tap(10,3)
        filled=await ev("(()=>{const m=window.DC2_STUDIO.doc.cart.maps.level1;let n=0;for(const r of m.layers[0].rows)for(let x=0;x<m.w;x++)if(parseInt(r.substr(x*2,2),36)===1)n++;return n})()")
        ck('fill floods the empty area (not the platform)', filled>300, filled)
        await pg.click('#btnUndo'); ck('fill is one undo step', await tileAt(0,10,3)==0)
        await pg.click('[data-tool=pick]'); await tap(5,12)
        st=await ev("({tile:window.DC2_STUDIO.mv.st.tile,layer:window.DC2_STUDIO.mv.st.layer,tool:window.DC2_STUDIO.mv.st.tool})")
        ck('pick takes the tile and its layer', st['tile']==3 and st['layer']==1 and st['tool']=='draw', st)

        print('C. things mode: place, select, edit, delete')
        await pg.click('#modeSeg [data-mode=things]'); await pg.click('#palette [data-prefab=coin]')
        n=await ev("window.DC2_STUDIO.doc.cart.maps.level1.objects.length")
        await tap(5,5)
        objs=await ev("window.DC2_STUDIO.doc.cart.maps.level1.objects")
        ck('tap places a coin at the tile centre', len(objs)==n+1 and objs[-1]['prefab']=='coin' and objs[-1]['x']==88 and objs[-1]['y']==88, objs[-1])
        await pg.click('[data-tool=select]'); await tap(5,5)
        await pg.wait_for_selector('.sheet'); ck('tapping it opens its inspector', 'Placed thing' in await pg.inner_text('.sheet-title'))
        await pg.fill('[data-path$="objects['+str(n)+'].x"] input','120')
        ck('editing X in the form updates the game', (await ev("window.DC2_STUDIO.doc.cart.maps.level1.objects[%d].x"%n))==120)
        await pg.click('.sheet .danger'); await pg.wait_for_timeout(100)
        ck('delete removes it', await ev("window.DC2_STUDIO.doc.cart.maps.level1.objects.length")==n)
        # drag an existing object (the walker)
        wi=await ev("window.DC2_STUDIO.doc.cart.maps.level1.objects.findIndex(o=>o.prefab==='walker')")
        w0=await ev("({x:window.DC2_STUDIO.doc.cart.maps.level1.objects[%d].x})"%wi); u0=await undos()
        await drag((12,11),(15,11))
        w1=await ev("window.DC2_STUDIO.doc.cart.maps.level1.objects[%d].x"%wi)
        ck('dragging moves an object by whole tiles', w1==w0['x']+48, (w0,w1))
        ck('a drag is one undo step', await undos()==u0+1)
        await pg.click('#btnUndo'); ck('undo puts it back', await ev("window.DC2_STUDIO.doc.cart.maps.level1.objects[%d].x"%wi)==w0['x'])
        while await pg.query_selector('.sheet'): await pg.click('.sheet-title [aria-label=close]'); await pg.wait_for_timeout(50)

        print('D. two-finger pinch zoom (real touch events)')
        s0=await ev("window.DC2_STUDIO.mv.view.s"); box=await pg.eval_on_selector('#mapCanvas','e=>{const r=e.getBoundingClientRect();return [r.left,r.top,r.width,r.height]}')
        cx,cy=box[0]+box[2]/2, box[1]+box[3]/2
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':cx-30,'y':cy,'id':1},{'x':cx+30,'y':cy,'id':2}]})
        for i in range(1,7): await cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':cx-30-i*12,'y':cy,'id':1},{'x':cx+30+i*12,'y':cy,'id':2}]})
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
        s1=await ev("window.DC2_STUDIO.mv.view.s"); ck('pinching zooms in', s1>s0*1.5, (s0,s1))
        nn=await undos(); ck('and paints nothing', True)
        await pg.click('#zFit'); await pg.click('#zFit')

        print('E. touch drawing')
        await pg.click('#modeSeg [data-mode=tiles]'); await pg.click('[data-tool=draw]')
        a=await cell(3,2); c=await cell(9,2)
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':a['x'],'y':a['y'],'id':1}]})
        for i in range(1,9): await cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':a['x']+(c['x']-a['x'])*i/8,'y':a['y'],'id':1}]})
        await cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
        row=[await tileAt(1,x,2) for x in range(3,10)]; ck('a finger paints a line on the selected layer', row==[3]*7, row)

        print('F. autosave + reload')
        await pg.wait_for_timeout(1200); ck('shows Saved', (await pg.inner_text('#saveState'))=='Saved', await pg.inner_text('#saveState'))
        await pg.reload(); await pg.wait_for_selector('#screenEditor:not([hidden])'); await pg.wait_for_timeout(600)
        row=[await tileAt(1,x,2) for x in range(3,10)]; ck('the stroke is still there after a reload', row==[3]*7, row)
        ck('and the project name', (await pg.inner_text('#projName'))=='UI Test')

        print('G. things editor')
        await pg.click('#tabs [data-tab=things]'); await pg.click('[data-thing=walker]'); await pg.wait_for_selector('.sheet')
        await pg.click('details[data-path="prefabs.walker.c.ai"] > summary')
        await pg.fill('[data-path="prefabs.walker.c.ai.speed"] input','40')
        ck('editing a part value', await ev("window.DC2_STUDIO.doc.cart.prefabs.walker.c.ai.speed")==40)
        ck('form shows friendly labels', 'Health' in await pg.inner_text('.sheet') and 'Rules' in await pg.inner_text('.sheet'))
        rc=await ev("window.DC2_STUDIO.doc.cart.prefabs.walker.rules.length")
        await pg.click('text=＋ Add a rule'); await pg.wait_for_selector('.pick-item'); await pg.click('.pick-item:has(b:text-is("Every"))')
        await pg.wait_for_timeout(200)
        ck('adding a rule from the picker', await ev("window.DC2_STUDIO.doc.cart.prefabs.walker.rules.length")==rc+1)
        nr=await ev("window.DC2_STUDIO.doc.cart.prefabs.walker.rules[window.DC2_STUDIO.doc.cart.prefabs.walker.rules.length-1]"); ck('the new rule is a valid blank', nr['on']=='every' and nr['then']==[], nr)
        await pg.locator('.card.rule').last.locator('text=＋ Add an action').click(); await pg.wait_for_selector('.pick-item'); await pg.click('.pick-item:has-text("Add")>> nth=0')
        await pg.wait_for_timeout(200)
        last=await ev("(()=>{const r=window.DC2_STUDIO.doc.cart.prefabs.walker.rules;return r[r.length-1].then})()"); ck('adding an action inside the rule', len(last)==1, last)
        await pg.wait_for_timeout(500)
        rep=await ev("window.DC2_STUDIO.report.errors.map(e=>e.path+': '+e.msg)")
        ck('problems are detected live for the unfinished action', any('walker.rules' in e for e in rep), rep)
        ck('and painted next to the field', await pg.locator('.sheet .issue').count()>0)
        await pg.click('.sheet .sh-undo'); await pg.click('.sheet .sh-undo'); await pg.wait_for_timeout(400)
        ck('undo works while the sheet is open', await ev("window.DC2_STUDIO.doc.cart.prefabs.walker.rules.length")==rc)
        # rename via UI
        await pg.click('.sheet-title [aria-label=close]'); await pg.click('[data-thing=slash]'); await pg.wait_for_selector('.sheet')
        await pg.click('.sheet >> text=Rename'); await pg.wait_for_selector('.big-in'); await pg.fill('.big-in','sword'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(300)
        ck('renaming updates every reference', await ev("window.DC2_STUDIO.doc.cart.prefabs['player-side'].rules[0].then[0].prefab")=='sword')
        ck('and the project stays valid', await ev("window.DC2_STUDIO.report.errors.length")==0, await ev("window.DC2_STUDIO.report.errors"))
        while await pg.query_selector('.sheet'): await pg.click('.sheet-title [aria-label=close]'); await pg.wait_for_timeout(50)

        print('H. play')
        await pg.click('#tabs [data-tab=play]'); await pg.wait_for_timeout(600)
        await pg.click('#tapStart')
        x0=await ev("window.DC2_STUDIO.runner.world.player().c.pos.x")
        await pg.keyboard.down('ArrowRight'); await pg.wait_for_timeout(700); await pg.keyboard.up('ArrowRight')
        x1=await ev("window.DC2_STUDIO.runner.world.player().c.pos.x"); ck('the game plays and responds to input', x1>x0+20, (x0,x1))
        ck('no runtime errors', await ev("window.DC2_STUDIO.runner.world.errors.length")==0)
        await pg.screenshot(path='/tmp/s2_play.png')

        print('I. levels')
        await pg.click('#tabs [data-tab=map]'); await pg.click('#lvlBtn'); await pg.click('text=＋ New level'); await pg.wait_for_selector('.big-in'); await pg.fill('.big-in','Cave'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(400)
        sc=await ev("Object.keys(window.DC2_STUDIO.doc.cart.scenes)"); ck('a new level is created', 'cave' in sc, sc)
        ck('the map switches to it', await ev("window.DC2_STUDIO.mv.st.mapId")=='cave')
        ck('with a player start', await ev("window.DC2_STUDIO.doc.cart.maps.cave.objects.some(o=>o.prefab==='player-side')"))
        await pg.click('#btnUndo'); await pg.wait_for_timeout(200)
        ck('undoing it removes level and scene', await ev("!window.DC2_STUDIO.doc.cart.maps.cave && !window.DC2_STUDIO.doc.cart.scenes.cave"))
        await pg.click('#btnRedo')

        print('J. export / import')
        await pg.click('#btnMenu'); 
        async with pg.expect_download() as dl: await pg.click('text=Export as .dcart file')
        d=await dl.value; path=await d.path(); txt=open(path).read(); ck('exports a .dcart file', json.loads(txt)['dcart']==1 and d.suggested_filename.endswith('.dcart'), d.suggested_filename)
        open('/tmp/export.dcart','w').write(txt)
        await pg.click('#btnBack'); await pg.wait_for_selector('.proj')
        await pg.set_input_files('#fileIn','/tmp/export.dcart'); await pg.wait_for_selector('#screenEditor:not([hidden])'); await pg.wait_for_timeout(400)
        ck('importing opens a copy', await ev("Object.keys(window.DC2_STUDIO.doc.cart.scenes).includes('cave')"))
        open('/tmp/bad.dcart','w').write(txt.replace('"coins": 0','"coins": 9'))
        await pg.click('#btnBack'); await pg.wait_for_selector('.proj'); await pg.set_input_files('#fileIn','/tmp/bad.dcart'); await pg.wait_for_timeout(500)
        ck('a tampered file is refused with a message', 'edited or damaged' in await pg.inner_text('#toast'), await pg.inner_text('#toast'))
        print('\nconsole/page errors:', errs if errs else 'none')
        print(f'{P} passed, {F} failed')
        await b.close()
asyncio.run(main())
